# Generated by Django 5.2.15 on 2026-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_id_staffcredentials_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('profile_view', 'Profile View'), ('expectation_update', 'Expectation Update'), ('photo_upload', 'Photo Upload'), ('account_deactivated', 'Account Deactivated'), ('account_activated', 'Account Activated'), ('role_changed', 'Role Changed'), ('payment', 'Payment')], max_length=30),
        ),
    ]
