services:
  - type: web
    name: nlm-backend
    env: python
    branch: main

    # Backend folder
    root: backend

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn matrimony.wsgi:application

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "true"

databases:
  - name: nlm-db
    databaseName: nlm_db
    plan: starter
