# Generated by Django 5.2.15 on 2026-07-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_birth_place_profile_birth_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('jain', 'Jain'), ('buddhist', 'Buddhist'), ('other', 'Other')], max_length=50),
        ),
    ]
